// Code generated by nanite-gsx. DO NOT EDIT.

package views

import (
"github.com/xDarkicex/gsx-demo/internal/db"

"github.com/xDarkicex/nanite-gsx"
"github.com/xDarkicex/nanite-render"
)

type CounterWidget struct{}


func RenderCounterWidget(c *render.ComponentContext, props map[string]any, children func(c *render.ComponentContext) error) error {
	c.WriteString(`<style>[x-cloak]{display:none!important}</style>`)
	c.WriteString(`<div`)
	c.WriteString(" class=\"card\"")
	c.WriteHydrateProps("x-data", map[string]any{"count": props["count"], "feature": props["feature"]})
	c.WriteString(">")
	c.WriteString(`<h2>`)
	c.WriteString(`Alpine.js, hydrated from Go`)
	c.WriteString(`</h2>`)
	c.WriteString(`<p`)
	c.WriteString(" class=\"muted\"")
	c.WriteString(">")
	c.WriteString(`This widget`)
	c.WriteString(`'s initial state was serialized by`)
	c.WriteString(`<code>`)
	c.WriteString(`c.WriteHydrateProps`)
	c.WriteString(`</code>`)
	c.WriteString(` — zero-alloc JSON from the
            server render. Clicks persist in libraVDB.
        `)
	c.WriteString(`</p>`)
	c.WriteString(`<div`)
	c.WriteString(" class=\"demo-row\"")
	c.WriteString(">")
	c.WriteString(`<button`)
	c.WriteString(" class=\"btn\"")
	c.WriteString(" name=\"click\"")
	c.WriteString(" value=\"1\"")
	c.WriteString(" hx-post=\"/_nano/action/CounterWidget/Increment\"")
	c.WriteString(" hx-target=\"closest div.card\"")
	c.WriteString(" hx-swap=\"outerHTML\"")
	c.WriteString(">")
	c.WriteString(`Clicked `)
	c.WriteString(`<span`)
	c.WriteString(" class=\"badge\"")
	c.WriteString(" x-text=\"count\"")
	c.WriteString(">")
	c.WriteString(`</span>`)
	c.WriteString(` times
            `)
	c.WriteString(`</button>`)
	c.WriteString(`<span`)
	c.WriteString(" class=\"badge\"")
	c.WriteString(" x-text=\"feature\"")
	c.WriteString(">")
	c.WriteString(`</span>`)
	c.WriteString(`</div>`)
	c.WriteString(`</div>`)
return nil
}

func RegisterCounterWidget(e *gsx.Engine) {
	e.Register("CounterWidget", func(c *render.ComponentContext, data any) error {
	return RenderCounterWidget(c, data.(map[string]any), nil)
	})
}

func RegisterCounterWidgetComponent(cr *render.ComponentRegistry) {
	cr.Define("CounterWidget").Action("Increment", func(rc *render.RenderContext, props map[string]any) error {

    n, err := db.Default.IncrementCounter(rc.Request.Context())
    if err != nil {
        return err
    }
    props["count"] = n
    if _, ok := props["feature"]; !ok {
        props["feature"] = "server-hydrated"
    }
    return nil

		}).Render(func(c *render.ComponentContext) error {
		return RenderCounterWidget(c, c.Data.(map[string]any), nil)
	}).Register(cr)
}
