// Code generated by nanite-gsx. DO NOT EDIT.

package views

import (
"fmt"
"html"
"github.com/xDarkicex/gsx-demo/models"
"time"

"github.com/xDarkicex/nanite-gsx"
"github.com/xDarkicex/nanite-render"
)

type Dashboard struct{}


func RenderDashboard(c *render.ComponentContext, p models.Page, children func(c *render.ComponentContext) error) error {
	c.WriteString(`<section`)
	c.WriteString(" class=\"cards\"")
	c.WriteString(">")
	if err := RenderStatCard(c, "Users", p.Dashboard.Stats.Users, "👥", nil); err != nil { return err }
	if err := RenderStatCard(c, "Following", p.Dashboard.Stats.Following, "→", nil); err != nil { return err }
	if err := RenderStatCard(c, "Suggestions", p.Dashboard.Stats.Suggestions, "✨", nil); err != nil { return err }
	c.WriteString(`</section>`)
	c.WriteString(`<div`)
	c.WriteString(" id=\"live-clock\"")
	c.WriteString(" hx-get=\"/widgets/clock\"")
	c.WriteString(" hx-trigger=\"load\"")
	c.WriteString(" hx-swap=\"innerHTML\"")
	c.WriteString(">")
	c.WriteString(`</div>`)
	c.WriteString(`<div`)
	c.WriteString(" class=\"grid-2\"")
	c.WriteString(">")
	if err := RenderFollowing(c, p, nil); err != nil { return err }
	if err := RenderSuggestedUsers(c, p, nil); err != nil { return err }
	c.WriteString(`</div>`)
return nil
}

func RegisterDashboard(e *gsx.Engine) {
	e.Register("Dashboard", func(c *render.ComponentContext, data any) error {
	return RenderDashboard(c, data.(models.Page), nil)
	})
}



type StatCard struct{}

type StatCardProps struct {
	Label string `nanite:"label"`
	Value int `nanite:"value"`
	Icon string `nanite:"icon"`
}

func RenderStatCard(c *render.ComponentContext, label string, value int, icon string, children func(c *render.ComponentContext) error) error {
	c.WriteString(`<div`)
	c.WriteString(" class=\"card stat-card\"")
	c.WriteString(">")
	c.WriteString(`<span`)
	c.WriteString(" class=\"stat-icon\"")
	c.WriteString(">")
	c.WriteString(html.EscapeString(fmt.Sprint(icon)))
	c.WriteString(`</span>`)
	c.WriteString(`<div>`)
	c.WriteString(`<div`)
	c.WriteString(" class=\"stat-value\"")
	c.WriteString(">")
	c.WriteString(html.EscapeString(fmt.Sprint(value)))
	c.WriteString(`</div>`)
	c.WriteString(`<div`)
	c.WriteString(" class=\"stat-label muted\"")
	c.WriteString(">")
	c.WriteString(html.EscapeString(fmt.Sprint(label)))
	c.WriteString(`</div>`)
	c.WriteString(`</div>`)
	c.WriteString(`</div>`)
return nil
}

func RegisterStatCard(e *gsx.Engine) {
	e.Register("StatCard", func(c *render.ComponentContext, data any) error {
	props := render.BindProps[StatCardProps](data)
	return RenderStatCard(c, props.Label, props.Value, props.Icon, nil)
	})
}



type LiveClock struct{}

func RenderLiveClock(c *render.ComponentContext, children func(c *render.ComponentContext) error) error {
	c.WriteString(`<div`)
	c.WriteString(" class=\"card clock\"")
	c.WriteString(">")
	c.WriteString(`<h2>`)
	c.WriteString(`Live clock `)
	c.WriteString(`<span`)
	c.WriteString(" class=\"muted\"")
	c.WriteString(">")
	c.WriteString(`(`)
	c.WriteString(`async + OOB)`)
	c.WriteString(`</span>`)
	c.WriteString(`</h2>`)
	c.WriteString(`<p`)
	c.WriteString(" class=\"clock-time\"")
	c.WriteString(">")
	c.WriteString(html.EscapeString(fmt.Sprint(time.Now().Format("15:04:05"))))
	c.WriteString(`</p>`)
	c.WriteString(`<p`)
	c.WriteString(" class=\"muted small\"")
	c.WriteString(">")
	c.WriteString(`Rendered in a worker goroutine after the page streamed —
            the skeleton appeared instantly, this HTML swapped in
            via `)
	c.WriteString(`<code>`)
	c.WriteString(`hx-swap-oob`)
	c.WriteString(`</code>`)
	c.WriteString(`.
        `)
	c.WriteString(`</p>`)
	c.WriteString(`</div>`)
return nil
}

func RegisterLiveClock(e *gsx.Engine) {
	e.Register("LiveClock", func(c *render.ComponentContext, data any) error {
	return RenderLiveClock(c, nil)
	})
}

func RegisterLiveClockComponent(cr *render.ComponentRegistry) {
	cr.Define("LiveClock").WithOOB("live-clock").Async().Fallback(func(c *render.ComponentContext) error { return RenderClockSkeleton(c, nil) }).Render(func(c *render.ComponentContext) error {
		return RenderLiveClock(c, nil)
	}).Register(cr)
}


type ClockSkeleton struct{}

func RenderClockSkeleton(c *render.ComponentContext, children func(c *render.ComponentContext) error) error {
	c.WriteString(`<div`)
	c.WriteString(" class=\"card clock\"")
	c.WriteString(">")
	c.WriteString(`<h2>`)
	c.WriteString(`Live clock`)
	c.WriteString(`</h2>`)
	c.WriteString(`<p`)
	c.WriteString(" class=\"clock-time skeleton-line\"")
	c.WriteString(">")
	c.WriteString(`Loading…`)
	c.WriteString(`</p>`)
	c.WriteString(`</div>`)
return nil
}

func RegisterClockSkeleton(e *gsx.Engine) {
	e.Register("ClockSkeleton", func(c *render.ComponentContext, data any) error {
	return RenderClockSkeleton(c, nil)
	})
}



type Following struct{}

func RenderFollowing(c *render.ComponentContext, page models.Page, children func(c *render.ComponentContext) error) error {
	c.WriteString(`<section`)
	c.WriteString(" class=\"card\"")
	c.WriteString(">")
	c.WriteString(`<h2>`)
	c.WriteString(`Following (`)
	c.WriteString(html.EscapeString(fmt.Sprint(len(page.Dashboard.Following))))
	c.WriteString(`)`)
	c.WriteString(`<button`)
	c.WriteString(" class=\"btn btn-sm\"")
	c.WriteString(" hx-get=\"/dashboard/partial/following\"")
	c.WriteString(" hx-target=\"#following\"")
	c.WriteString(" hx-swap=\"outerHTML\"")
	c.WriteString(">")
	c.WriteString(`⟳ Refresh
            `)
	c.WriteString(`</button>`)
	c.WriteString(`</h2>`)
	c.WriteString(`<ul`)
	c.WriteString(" class=\"people-list\"")
	c.WriteString(">")
	if len(page.Dashboard.Following) == 0 {
		c.WriteString(`<li`)
		c.WriteString(" class=\"muted\"")
		c.WriteString(">")
		c.WriteString(`Nobody yet — try following someone.`)
		c.WriteString(`</li>`)
	}
	for _, f := range page.Dashboard.Following {
		c.WriteString(`<li>`)
		c.WriteString(`<strong>`)
		c.WriteString(html.EscapeString(fmt.Sprint(f.Name)))
		c.WriteString(`</strong>`)
		c.WriteString(`<span`)
		c.WriteString(" class=\"muted\"")
		c.WriteString(">")
		c.WriteString(`@`)
		c.WriteString(html.EscapeString(fmt.Sprint(f.ID)))
		c.WriteString(`</span>`)
		c.WriteString(`</li>`)
	}
	c.WriteString(`</ul>`)
	c.WriteString(`</section>`)
return nil
}

func RegisterFollowing(e *gsx.Engine) {
	e.Register("Following", func(c *render.ComponentContext, data any) error {
	return RenderFollowing(c, data.(models.Page), nil)
	})
}



type SuggestedUsers struct{}

func RenderSuggestedUsers(c *render.ComponentContext, page models.Page, children func(c *render.ComponentContext) error) error {
	c.WriteString(`<section`)
	c.WriteString(" class=\"card\"")
	c.WriteString(">")
	c.WriteString(`<h2>`)
	c.WriteString(`Who to follow`)
	c.WriteString(`</h2>`)
	c.WriteString(`<ul`)
	c.WriteString(" class=\"people-list\"")
	c.WriteString(">")
	if len(page.Dashboard.Suggestions) == 0 {
		c.WriteString(`<li`)
		c.WriteString(" class=\"muted\"")
		c.WriteString(">")
		c.WriteString(`No suggestions — you`)
		c.WriteString(`'ve met everyone!`)
		c.WriteString(`</li>`)
	}
	for _, s := range page.Dashboard.Suggestions {
		c.WriteString(`<li>`)
		c.WriteString(`<div`)
		c.WriteString(" class=\"suggest-info\"")
		c.WriteString(">")
		c.WriteString(`<strong>`)
		c.WriteString(html.EscapeString(fmt.Sprint(s.Name)))
		c.WriteString(`</strong>`)
		c.WriteString(`<span`)
		c.WriteString(" class=\"muted\"")
		c.WriteString(">")
		c.WriteString(`@`)
		c.WriteString(html.EscapeString(fmt.Sprint(s.ID)))
		c.WriteString(` · `)
		c.WriteString(html.EscapeString(fmt.Sprint(s.Mutual)))
		c.WriteString(` mutual`)
		c.WriteString(`</span>`)
		c.WriteString(`</div>`)
		if err := RenderFollowButton(c, map[string]any{"target_id": s.ID, "followed": s.Followed}, nil); err != nil { return err }
		c.WriteString(`</li>`)
	}
	c.WriteString(`</ul>`)
	c.WriteString(`</section>`)
return nil
}

func RegisterSuggestedUsers(e *gsx.Engine) {
	e.Register("SuggestedUsers", func(c *render.ComponentContext, data any) error {
	return RenderSuggestedUsers(c, data.(models.Page), nil)
	})
}

