// Code generated by nanite-gsx. DO NOT EDIT.

package views

import (
"fmt"
"html"
"time"

"github.com/xDarkicex/nanite-gsx"
"github.com/xDarkicex/nanite-render"
)


type StatCardProps struct {
	Label string `nanite:"label"`
	Value int `nanite:"value"`
	Icon string `nanite:"icon"`
}

type StatCard struct{}


func RenderStatCard(c *render.ComponentContext, label string, value int, icon string, children func(c *render.ComponentContext) error) error {
	c.WriteString(`<article`)
	c.WriteString(" class=\"stat-card\"")
	c.WriteString(">")
	c.WriteString(`<div`)
	c.WriteString(" class=\"stat-card-top\"")
	c.WriteString(">")
	c.WriteString(`<span`)
	c.WriteString(" class=\"stat-icon\"")
	c.WriteString(">")
	c.WriteString(html.EscapeString(fmt.Sprint(icon)))
	c.WriteString(`</span>`)
	c.WriteString(`<span`)
	c.WriteString(" class=\"stat-trend\"")
	c.WriteString(">")
	c.WriteString(`+ live`)
	c.WriteString(`</span>`)
	c.WriteString(`</div>`)
	c.WriteString(`<div`)
	c.WriteString(" class=\"stat-value\"")
	c.WriteString(">")
	c.WriteString(html.EscapeString(fmt.Sprint(value)))
	c.WriteString(`</div>`)
	c.WriteString(`<div`)
	c.WriteString(" class=\"stat-label\"")
	c.WriteString(">")
	c.WriteString(html.EscapeString(fmt.Sprint(label)))
	c.WriteString(`</div>`)
	c.WriteString(`</article>`)
return nil
}

func RegisterStatCard(e *gsx.Engine) {
	e.Register("StatCard", func(c *render.ComponentContext, data any) error {
	props := render.BindProps[StatCardProps](data)
	return RenderStatCard(c, props.Label, props.Value, props.Icon, nil)
	})
}



type LiveClock struct{}

func RenderLiveClock(c *render.ComponentContext, children func(c *render.ComponentContext) error) error {
	c.WriteString(`<div`)
	c.WriteString(" class=\"card clock\"")
	c.WriteString(">")
	c.WriteString(`<h2>`)
	c.WriteString(`Live clock `)
	c.WriteString(`<span`)
	c.WriteString(" class=\"muted\"")
	c.WriteString(">")
	c.WriteString(`(`)
	c.WriteString(`async + OOB + Alpine tick)`)
	c.WriteString(`</span>`)
	c.WriteString(`</h2>`)
	c.WriteString(`<p`)
	c.WriteString(" class=\"clock-time\"")
	c.WriteHydrateProps("x-data", map[string]any{"now": time.Now().Format("15:04:05")})
	c.WriteString(" x-init=\"setInterval(() => now = new Date().toLocaleTimeString('en-GB', {hour12: false}), 1000)\"")
	c.WriteString(" x-text=\"now\"")
	c.WriteString(">")
	c.WriteString(html.EscapeString(fmt.Sprint(time.Now().Format("15:04:05"))))
	c.WriteString(`</p>`)
	c.WriteString(`<p`)
	c.WriteString(" class=\"muted small\"")
	c.WriteString(">")
	c.WriteString(`Rendered in a worker goroutine after the page streamed —
            the skeleton appeared instantly, this HTML swapped in
            via `)
	c.WriteString(`<code>`)
	c.WriteString(`hx-swap-oob`)
	c.WriteString(`</code>`)
	c.WriteString(`,`)
	c.WriteString(` and the time ticks via
            Alpine from the server-hydrated start value.
        `)
	c.WriteString(`</p>`)
	c.WriteString(`</div>`)
return nil
}

func RegisterLiveClock(e *gsx.Engine) {
	e.Register("LiveClock", func(c *render.ComponentContext, data any) error {
	return RenderLiveClock(c, nil)
	})
}

func RegisterLiveClockComponent(cr *render.ComponentRegistry) {
	cr.Define("LiveClock").WithOOB("live-clock").Async().Fallback(func(c *render.ComponentContext) error { return RenderClockSkeleton(c, nil) }).Render(func(c *render.ComponentContext) error {
		return RenderLiveClock(c, nil)
	}).Register(cr)
}


type ClockSkeleton struct{}

func RenderClockSkeleton(c *render.ComponentContext, children func(c *render.ComponentContext) error) error {
	c.WriteString(`<div`)
	c.WriteString(" class=\"card clock\"")
	c.WriteString(">")
	c.WriteString(`<h2>`)
	c.WriteString(`Live clock`)
	c.WriteString(`</h2>`)
	c.WriteString(`<p`)
	c.WriteString(" class=\"clock-time skeleton-line\"")
	c.WriteString(">")
	c.WriteString(`Loading…`)
	c.WriteString(`</p>`)
	c.WriteString(`</div>`)
return nil
}

func RegisterClockSkeleton(e *gsx.Engine) {
	e.Register("ClockSkeleton", func(c *render.ComponentContext, data any) error {
	return RenderClockSkeleton(c, nil)
	})
}

