// Code generated by nanite-gsx. DO NOT EDIT.

package views

import (
"fmt"
"html"
"github.com/xDarkicex/gsx-demo/models"
"github.com/xDarkicex/gsx-demo/internal/db"
"errors"

"github.com/xDarkicex/nanite-gsx"
"github.com/xDarkicex/nanite-render"
)

type Editor struct{}


func RenderEditor(c *render.ComponentContext, p models.Page, children func(c *render.ComponentContext) error) error {
	c.WriteString(`<style>[x-cloak]{display:none!important}</style>`)
	c.WriteString(`<div`)
	c.WriteString(" class=\"page-heading\"")
	c.WriteString(">")
	c.WriteString(`<div>`)
	c.WriteString(`<div`)
	c.WriteString(" class=\"eyebrow\"")
	c.WriteString(">")
	c.WriteString(`Data / Tables`)
	c.WriteString(`</div>`)
	c.WriteString(`<h1>`)
	c.WriteString(`Table editor`)
	c.WriteString(`</h1>`)
	c.WriteString(`<p`)
	c.WriteString(" class=\"page-subtitle\"")
	c.WriteString(">")
	c.WriteString(`Manage the `)
	c.WriteString(`<code>`)
	c.WriteString(`todos`)
	c.WriteString(`</code>`)
	c.WriteString(` table with fast, direct CRUD actions.`)
	c.WriteString(`</p>`)
	c.WriteString(`</div>`)
	c.WriteString(`<div`)
	c.WriteString(" class=\"heading-chip\"")
	c.WriteString(">")
	c.WriteString(`<span`)
	c.WriteString(" class=\"table-chip-icon\"")
	c.WriteString(">")
	c.WriteString(`▦`)
	c.WriteString(`</span>`)
	c.WriteString(` todos`)
	c.WriteString(`</div>`)
	c.WriteString(`</div>`)
	if p.Dash.TodoStat != "" {
		c.WriteString(`<div`)
		c.WriteString(" class=\"notice notice-success\"")
		c.WriteString(">")
		c.WriteString(`<span`)
		c.WriteString(" class=\"notice-icon\"")
		c.WriteString(">")
		c.WriteString(`✓`)
		c.WriteString(`</span>`)
		c.WriteString(html.EscapeString(fmt.Sprint(p.Dash.TodoStat)))
		c.WriteString(`</div>`)
	}
	c.WriteString(`<div`)
	c.WriteString(" class=\"editor-toolbar\"")
	c.WriteString(">")
	c.WriteString(`<form`)
	c.WriteString(" class=\"search-form\"")
	c.WriteString(" hx-get=\"/dashboard/editor/table\"")
	c.WriteString(" hx-target=\"#todo-table\"")
	c.WriteString(" hx-trigger=\"input changed delay:300ms\"")
	c.WriteString(" hx-swap=\"outerHTML\"")
	c.WriteString(">")
	c.WriteString(`<label`)
	c.WriteString(" class=\"sr-only\"")
	c.WriteString(" for=\"todo-search\"")
	c.WriteString(">")
	c.WriteString(`Search todos`)
	c.WriteString(`</label>`)
	c.WriteString(`<div`)
	c.WriteString(" class=\"search-input-wrap\"")
	c.WriteString(">")
	c.WriteString(`<span`)
	c.WriteString(" class=\"search-icon\"")
	c.WriteString(">")
	c.WriteString(`⌕`)
	c.WriteString(`</span>`)
	c.WriteString(`<input`)
	c.WriteString(" id=\"todo-search\"")
	c.WriteString(" class=\"uk-input search-input\"")
	c.WriteString(" type=\"search\"")
	c.WriteString(" name=\"q\"")
	c.WriteString(" placeholder=\"Search by title…\"")
	c.WriteString(" value=\"")
	c.WriteString(html.EscapeString(fmt.Sprint(p.Dash.TodoFilter)))
	c.WriteString("\"")
	c.WriteString(">")
	c.WriteString(`</input>`)
	c.WriteString(`</div>`)
	c.WriteString(`<button`)
	c.WriteString(" type=\"submit\"")
	c.WriteString(" class=\"uk-button uk-button-secondary search-button\"")
	c.WriteString(">")
	c.WriteString(`Search`)
	c.WriteString(`</button>`)
	c.WriteString(`</form>`)
	c.WriteString(`<button`)
	c.WriteString(" type=\"button\"")
	c.WriteString(" class=\"uk-button uk-button-primary add-todo-button\"")
	c.WriteString(" uk-toggle=\"target: #new-todo-modal\"")
	c.WriteString(">")
	c.WriteString(`<span`)
	c.WriteString(" class=\"button-plus\"")
	c.WriteString(">")
	c.WriteString(`+`)
	c.WriteString(`</span>`)
	c.WriteString(` New todo
        `)
	c.WriteString(`</button>`)
	c.WriteString(`</div>`)
	c.WriteString(`<div`)
	c.WriteString(" id=\"new-todo-modal\"")
	c.WriteString(" uk-modal=\"\"")
	c.WriteString(">")
	c.WriteString(`<div`)
	c.WriteString(" class=\"uk-modal-dialog dashboard-card\"")
	c.WriteString(">")
	c.WriteString(`<button`)
	c.WriteString(" class=\"uk-modal-close-default modal-close\"")
	c.WriteString(" type=\"button\"")
	c.WriteString(" uk-close=\"\"")
	c.WriteString(" aria-label=\"Close\"")
	c.WriteString(">")
	c.WriteString(`</button>`)
	c.WriteString(`<div`)
	c.WriteString(" class=\"card-heading\"")
	c.WriteString(">")
	c.WriteString(`<div>`)
	c.WriteString(`<div`)
	c.WriteString(" class=\"card-kicker\"")
	c.WriteString(">")
	c.WriteString(`Create record`)
	c.WriteString(`</div>`)
	c.WriteString(`<h2>`)
	c.WriteString(`New todo`)
	c.WriteString(`</h2>`)
	c.WriteString(`</div>`)
	c.WriteString(`</div>`)
	c.WriteString(`<form`)
	c.WriteString(" hx-post=\"/_nano/action/TodoTable/Save\"")
	c.WriteString(" hx-target=\"#todo-table\"")
	c.WriteString(" hx-swap=\"outerHTML\"")
	c.WriteString(" hx-on::after-swap=\"UIkit.modal('#new-todo-modal').hide(); UIkit.notification({message: 'Todo saved', status: 'success'})\"")
	c.WriteString(" hx-on::response-error=\"UIkit.notification({message: 'Save failed — check the fields', status: 'danger'})\"")
	c.WriteString(">")
	c.WriteString(`<div`)
	c.WriteString(" class=\"todo-form-grid\"")
	c.WriteString(">")
	c.WriteString(`<div`)
	c.WriteString(" class=\"field field-wide\"")
	c.WriteString(">")
	c.WriteString(`<label`)
	c.WriteString(" class=\"uk-form-label\"")
	c.WriteString(" for=\"todo-title\"")
	c.WriteString(">")
	c.WriteString(`Title`)
	c.WriteString(`</label>`)
	c.WriteString(`<input`)
	c.WriteString(" id=\"todo-title\"")
	c.WriteString(" class=\"uk-input\"")
	c.WriteString(" type=\"text\"")
	c.WriteString(" name=\"title\"")
	c.WriteString(" placeholder=\"Ship the modal\"")
	c.WriteString(" required=\"\"")
	c.WriteString(" autofocus=\"\"")
	c.WriteString(">")
	c.WriteString(`</input>`)
	c.WriteString(`</div>`)
	c.WriteString(`<div`)
	c.WriteString(" class=\"field\"")
	c.WriteString(">")
	c.WriteString(`<label`)
	c.WriteString(" class=\"uk-form-label\"")
	c.WriteString(" for=\"todo-priority\"")
	c.WriteString(">")
	c.WriteString(`Priority`)
	c.WriteString(`</label>`)
	c.WriteString(`<input`)
	c.WriteString(" id=\"todo-priority\"")
	c.WriteString(" class=\"uk-input\"")
	c.WriteString(" type=\"number\"")
	c.WriteString(" name=\"priority\"")
	c.WriteString(" value=\"3\"")
	c.WriteString(" min=\"1\"")
	c.WriteString(" max=\"5\"")
	c.WriteString(">")
	c.WriteString(`</input>`)
	c.WriteString(`</div>`)
	c.WriteString(`<div`)
	c.WriteString(" class=\"field\"")
	c.WriteString(">")
	c.WriteString(`<label`)
	c.WriteString(" class=\"uk-form-label\"")
	c.WriteString(" for=\"todo-status\"")
	c.WriteString(">")
	c.WriteString(`Status`)
	c.WriteString(`</label>`)
	c.WriteString(`<select`)
	c.WriteString(" id=\"todo-status\"")
	c.WriteString(" class=\"uk-select\"")
	c.WriteString(" name=\"completed\"")
	c.WriteString(">")
	c.WriteString(`<option`)
	c.WriteString(" value=\"false\"")
	c.WriteString(">")
	c.WriteString(`open`)
	c.WriteString(`</option>`)
	c.WriteString(`<option`)
	c.WriteString(" value=\"true\"")
	c.WriteString(">")
	c.WriteString(`closed`)
	c.WriteString(`</option>`)
	c.WriteString(`</select>`)
	c.WriteString(`</div>`)
	c.WriteString(`<div`)
	c.WriteString(" class=\"field\"")
	c.WriteString(">")
	c.WriteString(`<label`)
	c.WriteString(" class=\"uk-form-label\"")
	c.WriteString(" for=\"todo-opened\"")
	c.WriteString(">")
	c.WriteString(`Opened date`)
	c.WriteString(`</label>`)
	c.WriteString(`<input`)
	c.WriteString(" id=\"todo-opened\"")
	c.WriteString(" class=\"uk-input\"")
	c.WriteString(" type=\"text\"")
	c.WriteString(" name=\"opened_at\"")
	c.WriteString(" placeholder=\"2026-08-11 09:00:00\"")
	c.WriteString(">")
	c.WriteString(`</input>`)
	c.WriteString(`</div>`)
	c.WriteString(`<div`)
	c.WriteString(" class=\"field\"")
	c.WriteString(">")
	c.WriteString(`<label`)
	c.WriteString(" class=\"uk-form-label\"")
	c.WriteString(" for=\"todo-due\"")
	c.WriteString(">")
	c.WriteString(`Due date`)
	c.WriteString(`</label>`)
	c.WriteString(`<input`)
	c.WriteString(" id=\"todo-due\"")
	c.WriteString(" class=\"uk-input\"")
	c.WriteString(" type=\"text\"")
	c.WriteString(" name=\"due_at\"")
	c.WriteString(" placeholder=\"2026-08-15 12:00:00\"")
	c.WriteString(">")
	c.WriteString(`</input>`)
	c.WriteString(`</div>`)
	c.WriteString(`<div`)
	c.WriteString(" class=\"field field-wide\"")
	c.WriteString(" x-data=\"{tags: [], draft: '', addTag() { var t = this.draft.trim().replace(/,+$/, ''); if (t && !this.tags.includes(t)) { this.tags.push(t); } this.draft = ''; }}\"")
	c.WriteString(">")
	c.WriteString(`<label`)
	c.WriteString(" class=\"uk-form-label\"")
	c.WriteString(">")
	c.WriteString(`Tags`)
	c.WriteString(`</label>`)
	c.WriteString(`<div`)
	c.WriteString(" class=\"tag-input-wrap\"")
	c.WriteString(">")
	c.WriteString(`<div`)
	c.WriteString(" class=\"tag-chips\"")
	c.WriteString(">")
	c.WriteString(`<template`)
	c.WriteString(" x-for=\"t in tags\"")
	c.WriteString(" :key=\"t\"")
	c.WriteString(">")
	c.WriteString(`<span`)
	c.WriteString(" class=\"tag-chip\"")
	c.WriteString(" x-text=\"t\"")
	c.WriteString(" @click=\"tags = tags.filter(x => x !== t)\"")
	c.WriteString(">")
	c.WriteString(`</span>`)
	c.WriteString(`</template>`)
	c.WriteString(`</div>`)
	c.WriteString(`<input`)
	c.WriteString(" id=\"todo-tags\"")
	c.WriteString(" class=\"uk-input\"")
	c.WriteString(" type=\"text\"")
	c.WriteString(" x-model=\"draft\"")
	c.WriteString(" @keydown.enter.prevent=\"addTag\"")
	c.WriteString(" @keydown=\"if ($event.key === ',') { $event.preventDefault(); addTag() }\"")
	c.WriteString(" placeholder=\"ops, docs\"")
	c.WriteString(">")
	c.WriteString(`</input>`)
	c.WriteString(`</div>`)
	c.WriteString(`<input`)
	c.WriteString(" type=\"hidden\"")
	c.WriteString(" name=\"tags\"")
	c.WriteString(" :value=\"JSON.stringify(tags)\"")
	c.WriteString(">")
	c.WriteString(`</input>`)
	c.WriteString(`</div>`)
	c.WriteString(`</div>`)
	c.WriteString(`<div`)
	c.WriteString(" class=\"form-actions\"")
	c.WriteString(">")
	c.WriteString(`<button`)
	c.WriteString(" type=\"button\"")
	c.WriteString(" class=\"uk-button uk-button-secondary\"")
	c.WriteString(" uk-toggle=\"target: #new-todo-modal\"")
	c.WriteString(">")
	c.WriteString(`Cancel`)
	c.WriteString(`</button>`)
	c.WriteString(`<button`)
	c.WriteString(" type=\"submit\"")
	c.WriteString(" class=\"uk-button uk-button-primary\"")
	c.WriteString(">")
	c.WriteString(`Save todo`)
	c.WriteString(`</button>`)
	c.WriteString(`</div>`)
	c.WriteString(`</form>`)
	c.WriteString(`</div>`)
	c.WriteString(`</div>`)
	c.WriteString(`<div`)
	c.WriteString(" id=\"todo-table\"")
	c.WriteString(">")
	if err := RenderTodoTable(c, map[string]any{"todos": p.Dash.Todos, "filter": p.Dash.TodoFilter}, nil); err != nil { return err }
	c.WriteString(`</div>`)
return nil
}

func RegisterEditor(e *gsx.Engine) {
	e.Register("Editor", func(c *render.ComponentContext, data any) error {
	return RenderEditor(c, data.(models.Page), nil)
	})
}



type TodoTable struct{}

func RenderTodoTable(c *render.ComponentContext, props map[string]any, children func(c *render.ComponentContext) error) error {
	c.WriteString(`<section`)
	c.WriteString(" class=\"dashboard-card table-card\"")
	c.WriteString(">")
	c.WriteString(`<div`)
	c.WriteString(" class=\"table-card-header\"")
	c.WriteString(">")
	c.WriteString(`<div>`)
	c.WriteString(`<div`)
	c.WriteString(" class=\"card-kicker\"")
	c.WriteString(">")
	c.WriteString(`All records`)
	c.WriteString(`</div>`)
	c.WriteString(`<h2>`)
	c.WriteString(`Todo list`)
	c.WriteString(`</h2>`)
	c.WriteString(`</div>`)
	c.WriteString(`<span`)
	c.WriteString(" class=\"record-count\"")
	c.WriteString(">")
	c.WriteString(html.EscapeString(fmt.Sprint(len(props["todos"].([]models.Todo)))))
	c.WriteString(` records`)
	c.WriteString(`</span>`)
	c.WriteString(`</div>`)
	c.WriteString(`<div`)
	c.WriteString(" class=\"table-scroll\"")
	c.WriteString(">")
	c.WriteString(`<table`)
	c.WriteString(" class=\"uk-table todo-table\"")
	c.WriteString(">")
	c.WriteString(`<thead>`)
	c.WriteString(`<tr>`)
	c.WriteString(`<th>`)
	c.WriteString(`Task`)
	c.WriteString(`</th>`)
	c.WriteString(`<th>`)
	c.WriteString(`Status`)
	c.WriteString(`</th>`)
	c.WriteString(`<th>`)
	c.WriteString(`Priority`)
	c.WriteString(`</th>`)
	c.WriteString(`<th>`)
	c.WriteString(`Due`)
	c.WriteString(`</th>`)
	c.WriteString(`<th>`)
	c.WriteString(`Tags`)
	c.WriteString(`</th>`)
	c.WriteString(`<th`)
	c.WriteString(" class=\"actions-column\"")
	c.WriteString(">")
	c.WriteString(`Actions`)
	c.WriteString(`</th>`)
	c.WriteString(`</tr>`)
	c.WriteString(`</thead>`)
	c.WriteString(`<tbody>`)
	for _, t := range props["todos"].([]models.Todo) {
		if err := RenderTodoRow(c, map[string]any{
                            "id": t.ID, "title": t.Title, "completed": t.Completed,
                            "priority": t.Priority, "due_at": t.DueAt, "tags": t.Tags,
                        }, nil); err != nil { return err }
	}
	if len(props["todos"].([]models.Todo)) == 0 {
		c.WriteString(`<tr>`)
		c.WriteString(`<td`)
		c.WriteString(" colspan=\"6\"")
		c.WriteString(" class=\"empty-table\"")
		c.WriteString(">")
		c.WriteString(`No todos match your search.`)
		c.WriteString(`</td>`)
		c.WriteString(`</tr>`)
	}
	c.WriteString(`</tbody>`)
	c.WriteString(`</table>`)
	c.WriteString(`</div>`)
	c.WriteString(`</section>`)
return nil
}

func RegisterTodoTable(e *gsx.Engine) {
	e.Register("TodoTable", func(c *render.ComponentContext, data any) error {
	return RenderTodoTable(c, data.(map[string]any), nil)
	})
}

func RegisterTodoTableComponent(cr *render.ComponentRegistry) {
	cr.Define("TodoTable").Action("Save", func(rc *render.RenderContext, props map[string]any) error {

    title, _ := props["title"].(string)
    if title == "" {
        return errors.New("title is required")
    }
    openedAt, _ := props["opened_at"].(string)
    dueAt, _ := props["due_at"].(string)
    tags, _ := props["tags"].(string)
    t := &models.Todo{
        Title:     title,
        Priority:  3,
        OpenedAt:  openedAt,
        DueAt:     dueAt,
        Tags:      tags,
        Completed: props["completed"] == true,
    }
    if p, ok := props["priority"].(int); ok && p >= 1 && p <= 5 {
        t.Priority = p
    }
    if err := db.Default.SaveTodo(rc.Request.Context(), t); err != nil {
        return err
    }
    ts, err := db.Default.Todos(rc.Request.Context(), "")
    if err != nil {
        return err
    }
    props["todos"] = ts
    props["filter"] = ""
    return nil

		}).Render(func(c *render.ComponentContext) error {
		return RenderTodoTable(c, c.Data.(map[string]any), nil)
	}).Register(cr)
}


type TodoRow struct{}

func RenderTodoRow(c *render.ComponentContext, props map[string]any, children func(c *render.ComponentContext) error) error {
	c.WriteString(`<tr`)
	c.WriteString(" class=\"")
	c.WriteString(html.EscapeString(fmt.Sprint(todoRowClass(props["completed"] == true))))
	c.WriteString("\"")
	c.WriteString(">")
	c.WriteString(`<td`)
	c.WriteString(" class=\"todo-title-cell\"")
	c.WriteString(">")
	c.WriteString(`<span`)
	c.WriteString(" class=\"")
	c.WriteString(html.EscapeString(fmt.Sprint(todoMarkerClass(props["completed"] == true))))
	c.WriteString("\"")
	c.WriteString(">")
	c.WriteString(`</span>`)
	c.WriteString(`<strong>`)
	c.WriteString(html.EscapeString(fmt.Sprint(props["title"])))
	c.WriteString(`</strong>`)
	c.WriteString(`</td>`)
	c.WriteString(`<td>`)
	if props["completed"] == true {
		c.WriteString(`<span`)
		c.WriteString(" class=\"status-pill status-done\"")
		c.WriteString(">")
		c.WriteString(`done`)
		c.WriteString(`</span>`)
	} else {
		c.WriteString(`<span`)
		c.WriteString(" class=\"status-pill status-open\"")
		c.WriteString(">")
		c.WriteString(`open`)
		c.WriteString(`</span>`)
	}
	c.WriteString(`</td>`)
	c.WriteString(`<td>`)
	c.WriteString(`<span`)
	c.WriteString(" class=\"priority-pill\"")
	c.WriteString(">")
	c.WriteString(`P`)
	c.WriteString(html.EscapeString(fmt.Sprint(props["priority"])))
	c.WriteString(`</span>`)
	c.WriteString(`</td>`)
	c.WriteString(`<td`)
	c.WriteString(" class=\"muted\"")
	c.WriteString(">")
	c.WriteString(html.EscapeString(fmt.Sprint(props["due_at"])))
	c.WriteString(`</td>`)
	c.WriteString(`<td`)
	c.WriteString(" class=\"muted small\"")
	c.WriteString(">")
	c.WriteString(html.EscapeString(fmt.Sprint(props["tags"])))
	c.WriteString(`</td>`)
	c.WriteString(`<td`)
	c.WriteString(" class=\"row-actions\"")
	c.WriteString(">")
	c.WriteString(`<form`)
	c.WriteString(" class=\"action-form\"")
	c.WriteString(" hx-post=\"/_nano/action/TodoRow/Toggle\"")
	c.WriteString(" hx-target=\"closest tr\"")
	c.WriteString(" hx-swap=\"outerHTML\"")
	c.WriteString(">")
	c.WriteString(`<input`)
	c.WriteString(" type=\"hidden\"")
	c.WriteString(" name=\"id\"")
	c.WriteString(" value=\"")
	c.WriteString(html.EscapeString(fmt.Sprint(props["id"].(string))))
	c.WriteString("\"")
	c.WriteString(">")
	c.WriteString(`</input>`)
	c.WriteString(`<input`)
	c.WriteString(" type=\"hidden\"")
	c.WriteString(" name=\"completed\"")
	c.WriteString(" value=\"")
	c.WriteString(html.EscapeString(fmt.Sprint(props["completed"])))
	c.WriteString("\"")
	c.WriteString(">")
	c.WriteString(`</input>`)
	c.WriteString(`<button`)
	c.WriteString(" type=\"submit\"")
	c.WriteString(" class=\"uk-button uk-button-small uk-button-secondary action-button\"")
	c.WriteString(">")
	if props["completed"] == true {
		c.WriteString(`Mark open
                    `)
	} else {
		c.WriteString(`Mark done
                    `)
	}
	c.WriteString(`</button>`)
	c.WriteString(`</form>`)
	c.WriteString(`<form`)
	c.WriteString(" class=\"action-form\"")
	c.WriteString(" hx-post=\"/_nano/action/TodoRow/Delete\"")
	c.WriteString(" hx-target=\"closest tr\"")
	c.WriteString(" hx-swap=\"delete\"")
	c.WriteString(">")
	c.WriteString(`<input`)
	c.WriteString(" type=\"hidden\"")
	c.WriteString(" name=\"id\"")
	c.WriteString(" value=\"")
	c.WriteString(html.EscapeString(fmt.Sprint(props["id"].(string))))
	c.WriteString("\"")
	c.WriteString(">")
	c.WriteString(`</input>`)
	c.WriteString(`<button`)
	c.WriteString(" type=\"submit\"")
	c.WriteString(" class=\"uk-button uk-button-small uk-button-ghost action-button action-delete\"")
	c.WriteString(">")
	c.WriteString(`Delete`)
	c.WriteString(`</button>`)
	c.WriteString(`</form>`)
	c.WriteString(`</td>`)
	c.WriteString(`</tr>`)
return nil
}

func RegisterTodoRow(e *gsx.Engine) {
	e.Register("TodoRow", func(c *render.ComponentContext, data any) error {
	return RenderTodoRow(c, data.(map[string]any), nil)
	})
}

func RegisterTodoRowComponent(cr *render.ComponentRegistry) {
	cr.Define("TodoRow").Action("Toggle", func(rc *render.RenderContext, props map[string]any) error {

    id := props["id"].(string)
    if err := db.Default.ToggleTodo(rc.Request.Context(), id); err != nil {
        return err
    }
    // Reload the full record — the re-render needs every field,
    // not just the id from the form.
    t, err := db.Default.TodoByID(rc.Request.Context(), id)
    if err != nil {
        return err
    }
    props["id"] = t.ID
    props["title"] = t.Title
    props["completed"] = t.Completed
    props["priority"] = t.Priority
    props["due_at"] = t.DueAt
    props["tags"] = t.Tags
    return nil

		}).Action("Delete", func(rc *render.RenderContext, props map[string]any) error {

    id := props["id"].(string)
    if err := db.Default.DeleteTodo(rc.Request.Context(), id); err != nil {
        return err
    }
    return nil // htmx swap:delete removes the row; body ignored

		}).Render(func(c *render.ComponentContext) error {
		return RenderTodoRow(c, c.Data.(map[string]any), nil)
	}).Register(cr)
}
