// Code generated by nanite-gsx. DO NOT EDIT.

package views

import (
"fmt"
"html"
"github.com/xDarkicex/gsx-demo/models"

"github.com/xDarkicex/nanite-gsx"
"github.com/xDarkicex/nanite-render"
)

type ErrorPage struct{}


func RenderErrorPage(c *render.ComponentContext, p models.Page, children func(c *render.ComponentContext) error) error {
	c.WriteString(`<div`)
	c.WriteString(" class=\"auth-shell\"")
	c.WriteString(">")
	c.WriteString(`<div`)
	c.WriteString(" class=\"auth-card error-card\"")
	c.WriteString(">")
	c.WriteString(`<div`)
	c.WriteString(" class=\"auth-brand\"")
	c.WriteString(">")
	c.WriteString(`<span`)
	c.WriteString(" class=\"auth-logo\"")
	c.WriteString(">")
	c.WriteString(`&lt;/&gt;`)
	c.WriteString(`</span>`)
	c.WriteString(`<span`)
	c.WriteString(" class=\"auth-brand-name\"")
	c.WriteString(">")
	c.WriteString(`gsx-studio`)
	c.WriteString(`</span>`)
	c.WriteString(`</div>`)
	c.WriteString(`<div`)
	c.WriteString(" class=\"error-code\"")
	c.WriteString(">")
	c.WriteString(html.EscapeString(fmt.Sprint(p.Error.Code)))
	c.WriteString(`</div>`)
	c.WriteString(`<h1`)
	c.WriteString(" class=\"auth-title\"")
	c.WriteString(">")
	c.WriteString(html.EscapeString(fmt.Sprint(p.Error.Title)))
	c.WriteString(`</h1>`)
	c.WriteString(`<p`)
	c.WriteString(" class=\"auth-subtitle\"")
	c.WriteString(">")
	c.WriteString(html.EscapeString(fmt.Sprint(p.Error.Message)))
	c.WriteString(`</p>`)
	c.WriteString(`<div`)
	c.WriteString(" class=\"form-actions\"")
	c.WriteString(">")
	c.WriteString(`<a`)
	c.WriteString(" class=\"uk-button uk-button-primary\"")
	c.WriteString(" href=\"/dashboard\"")
	c.WriteString(">")
	c.WriteString(`Back to dashboard`)
	c.WriteString(`</a>`)
	c.WriteString(`</div>`)
	c.WriteString(`</div>`)
	c.WriteString(`</div>`)
return nil
}

func RegisterErrorPage(e *gsx.Engine) {
	e.Register("ErrorPage", func(c *render.ComponentContext, data any) error {
	return RenderErrorPage(c, data.(models.Page), nil)
	})
}

