// Code generated by nanite-gsx. DO NOT EDIT.

package views

import (
"html"
"fmt"
"errors"
"github.com/xDarkicex/gsx-demo/internal/auth"
"github.com/xDarkicex/gsx-demo/internal/db"

"github.com/xDarkicex/nanite-gsx"
"github.com/xDarkicex/nanite-render"
)

type FollowButton struct{}


func RenderFollowButton(c *render.ComponentContext, props map[string]any, children func(c *render.ComponentContext) error) error {
	if v, ok := props["target_id"].(string); ok {
		if props["followed"] == true {
			c.WriteString(`<form`)
			c.WriteString(" hx-post=\"/_nano/action/FollowButton/Follow\"")
			c.WriteString(" hx-target=\"closest li\"")
			c.WriteString(" hx-swap=\"outerHTML\"")
			c.WriteString(">")
			c.WriteString(`<input`)
			c.WriteString(" type=\"hidden\"")
			c.WriteString(" name=\"target_id\"")
			c.WriteString(" value=\"")
			c.WriteString(html.EscapeString(fmt.Sprint(v)))
			c.WriteString("\"")
			c.WriteString(">")
			c.WriteString(`</input>`)
			c.WriteString(`<input`)
			c.WriteString(" type=\"hidden\"")
			c.WriteString(" name=\"followed\"")
			c.WriteString(" value=\"true\"")
			c.WriteString(">")
			c.WriteString(`</input>`)
			c.WriteString(`<button`)
			c.WriteString(" type=\"submit\"")
			c.WriteString(" class=\"btn btn-sm\"")
			c.WriteString(">")
			c.WriteString(`✓ Following`)
			c.WriteString(`</button>`)
			c.WriteString(`</form>`)
		} else {
			c.WriteString(`<form`)
			c.WriteString(" hx-post=\"/_nano/action/FollowButton/Follow\"")
			c.WriteString(" hx-target=\"closest li\"")
			c.WriteString(" hx-swap=\"outerHTML\"")
			c.WriteString(">")
			c.WriteString(`<input`)
			c.WriteString(" type=\"hidden\"")
			c.WriteString(" name=\"target_id\"")
			c.WriteString(" value=\"")
			c.WriteString(html.EscapeString(fmt.Sprint(v)))
			c.WriteString("\"")
			c.WriteString(">")
			c.WriteString(`</input>`)
			c.WriteString(`<input`)
			c.WriteString(" type=\"hidden\"")
			c.WriteString(" name=\"followed\"")
			c.WriteString(" value=\"false\"")
			c.WriteString(">")
			c.WriteString(`</input>`)
			c.WriteString(`<button`)
			c.WriteString(" type=\"submit\"")
			c.WriteString(" class=\"btn btn-sm btn-primary\"")
			c.WriteString(">")
			c.WriteString(`+ Follow`)
			c.WriteString(`</button>`)
			c.WriteString(`</form>`)
		}
	}
	if __err := c.Context.GetFormError("target"); __err != "" {
		c.WriteString("<span class=\"error\">")
		c.WriteString(html.EscapeString(__err))
		c.WriteString("</span>")
	}
return nil
}

func RegisterFollowButton(e *gsx.Engine) {
	e.Register("FollowButton", func(c *render.ComponentContext, data any) error {
	return RenderFollowButton(c, data.(map[string]any), nil)
	})
}

func RegisterFollowButtonComponent(cr *render.ComponentRegistry) {
	cr.Define("FollowButton").Action("Follow", func(rc *render.RenderContext, props map[string]any) error {

    me := auth.UserFromRequest(rc.Request)
    if me == nil {
        return errors.New("unauthenticated")
    }
    target, _ := props["target_id"].(string)
    if target == "" {
        rc.SetFormError("target", "Missing target user")
        return render.ErrValidation
    }
    if props["followed"] == true {
        props["followed"] = false
        return db.Default.Unfollow(rc.Request.Context(), me.ID, target)
    }
    props["followed"] = true
    return db.Default.Follow(rc.Request.Context(), me.ID, target)

		}).Render(func(c *render.ComponentContext) error {
		return RenderFollowButton(c, c.Data.(map[string]any), nil)
	}).Register(cr)
	cr.Memoize("FollowButton", func(rc *render.RenderContext, data any) string {
		props := data.(map[string]any)
		
    return fmt.Sprint(props["target_id"], "/", props["followed"])

	})
}
