// Code generated by nanite-gsx. DO NOT EDIT.

package views

import (
"fmt"
"html"
"github.com/xDarkicex/gsx-demo/models"

"github.com/xDarkicex/nanite-gsx"
"github.com/xDarkicex/nanite-render"
)

type Home struct{}


func RenderHome(c *render.ComponentContext, p models.Page, children func(c *render.ComponentContext) error) error {
	c.WriteString(`<style>[x-cloak]{display:none!important}</style>`)
	c.WriteString(`<section`)
	c.WriteString(" class=\"hero\"")
	c.WriteString(">")
	c.WriteString(`<h1>`)
	c.WriteString(`The nanite stack, in one page`)
	c.WriteString(`</h1>`)
	c.WriteString(`<p`)
	c.WriteString(" class=\"lead\"")
	c.WriteString(">")
	c.WriteString(`<code>`)
	c.WriteString(`nanite`)
	c.WriteString(`</code>`)
	c.WriteString(` router · `)
	c.WriteString(`<code>`)
	c.WriteString(`nanite-render`)
	c.WriteString(`</code>`)
	c.WriteString(` engine ·
            `)
	c.WriteString(`<code>`)
	c.WriteString(`nanite-gsx`)
	c.WriteString(`</code>`)
	c.WriteString(` templates · `)
	c.WriteString(`<code>`)
	c.WriteString(`libraVDB`)
	c.WriteString(`</code>`)
	c.WriteString(` relational + graph.
        `)
	c.WriteString(`</p>`)
	c.WriteString(`<div`)
	c.WriteString(" class=\"hero-actions\"")
	c.WriteString(">")
	if p.User != nil {
		c.WriteString(`<a`)
		c.WriteString(" class=\"btn btn-primary btn-lg\"")
		c.WriteString(" href=\"/dashboard\"")
		c.WriteString(">")
		c.WriteString(`Open dashboard`)
		c.WriteString(`</a>`)
	} else {
		c.WriteString(`<a`)
		c.WriteString(" class=\"btn btn-primary btn-lg\"")
		c.WriteString(" href=\"/login\"")
		c.WriteString(">")
		c.WriteString(`Sign in`)
		c.WriteString(`</a>`)
	}
	c.WriteString(`</div>`)
	c.WriteString(`<p`)
	c.WriteString(" class=\"muted\"")
	c.WriteString(">")
	c.WriteString(html.EscapeString(fmt.Sprint(p.Home.UserCount)))
	c.WriteString(` users in libraVDB`)
	c.WriteString(`</p>`)
	c.WriteString(`</section>`)
	c.WriteString(`<section`)
	c.WriteString(" class=\"card\"")
	c.WriteHydrateProps("x-data", map[string]any{"count": 0, "feature": p.Home.Feature})
	c.WriteString(">")
	c.WriteString(`<h2>`)
	c.WriteString(`Alpine.js, hydrated from Go`)
	c.WriteString(`</h2>`)
	c.WriteString(`<p`)
	c.WriteString(" class=\"muted\"")
	c.WriteString(">")
	c.WriteString(`This widget`)
	c.WriteString(`'s initial state was serialized by`)
	c.WriteString(`<code>`)
	c.WriteString(`c.WriteHydrateProps`)
	c.WriteString(`</code>`)
	c.WriteString(` — zero-alloc JSON from the
            server render.
        `)
	c.WriteString(`</p>`)
	c.WriteString(`<div`)
	c.WriteString(" class=\"demo-row\"")
	c.WriteString(">")
	c.WriteString(`<button`)
	c.WriteString(" class=\"btn\"")
	c.WriteString(" @click=\"count++\"")
	c.WriteString(">")
	c.WriteString(`Clicked `)
	c.WriteString(`<span`)
	c.WriteString(" class=\"badge\"")
	c.WriteString(" x-text=\"count\"")
	c.WriteString(">")
	c.WriteString(`</span>`)
	c.WriteString(` times
            `)
	c.WriteString(`</button>`)
	c.WriteString(`<span`)
	c.WriteString(" class=\"badge\"")
	c.WriteString(" x-text=\"feature\"")
	c.WriteString(">")
	c.WriteString(`</span>`)
	c.WriteString(`</div>`)
	c.WriteString(`</section>`)
	c.WriteString(`<section`)
	c.WriteString(" class=\"card\"")
	c.WriteString(">")
	c.WriteString(`<h2>`)
	c.WriteString(`Leaderboard — a graph query`)
	c.WriteString(`</h2>`)
	c.WriteString(`<p`)
	c.WriteString(" class=\"muted\"")
	c.WriteString(">")
	c.WriteString(`Top users by follower count, computed with libraVDB
            `)
	c.WriteString(`<code>`)
	c.WriteString(`JOIN MATCH`)
	c.WriteString(`</code>`)
	c.WriteString(` over the FOLLOWS graph.
        `)
	c.WriteString(`</p>`)
	c.WriteString(`<ol`)
	c.WriteString(" class=\"leaderboard\"")
	c.WriteString(">")
	for _, f := range p.Home.FollowerTop {
		c.WriteString(`<li>`)
		c.WriteString(`<strong>`)
		c.WriteString(html.EscapeString(fmt.Sprint(f.Name)))
		c.WriteString(`</strong>`)
		c.WriteString(`<span`)
		c.WriteString(" class=\"muted\"")
		c.WriteString(">")
		c.WriteString(`@`)
		c.WriteString(html.EscapeString(fmt.Sprint(f.ID)))
		c.WriteString(` · `)
		c.WriteString(html.EscapeString(fmt.Sprint(f.Followers)))
		c.WriteString(` followers`)
		c.WriteString(`</span>`)
		c.WriteString(`</li>`)
	}
	c.WriteString(`</ol>`)
	c.WriteString(`</section>`)
return nil
}

func RegisterHome(e *gsx.Engine) {
	e.Register("Home", func(c *render.ComponentContext, data any) error {
	return RenderHome(c, data.(models.Page), nil)
	})
}

