// Code generated by nanite-gsx. DO NOT EDIT.

package views

import (
"fmt"
"html"
"github.com/xDarkicex/gsx-demo/models"

"github.com/xDarkicex/nanite-gsx"
"github.com/xDarkicex/nanite-render"
)

type Home struct{}


func RenderHome(c *render.ComponentContext, p models.Page, children func(c *render.ComponentContext) error) error {
	c.WriteString(`<section`)
	c.WriteString(" class=\"hero\"")
	c.WriteString(">")
	c.WriteString(`<h1>`)
	c.WriteString(`The nanite stack, in one page`)
	c.WriteString(`</h1>`)
	c.WriteString(`<p`)
	c.WriteString(" class=\"lead\"")
	c.WriteString(">")
	c.WriteString(`<code>`)
	c.WriteString(`nanite`)
	c.WriteString(`</code>`)
	c.WriteString(` router · `)
	c.WriteString(`<code>`)
	c.WriteString(`nanite-render`)
	c.WriteString(`</code>`)
	c.WriteString(` engine ·
            `)
	c.WriteString(`<code>`)
	c.WriteString(`nanite-gsx`)
	c.WriteString(`</code>`)
	c.WriteString(` templates · `)
	c.WriteString(`<code>`)
	c.WriteString(`libraVDB`)
	c.WriteString(`</code>`)
	c.WriteString(` relational + graph.
        `)
	c.WriteString(`</p>`)
	c.WriteString(`<div`)
	c.WriteString(" class=\"hero-actions\"")
	c.WriteString(">")
	if p.User != nil {
		c.WriteString(`<a`)
		c.WriteString(" class=\"btn btn-primary btn-lg\"")
		c.WriteString(" href=\"/dashboard\"")
		c.WriteString(">")
		c.WriteString(`Open dashboard`)
		c.WriteString(`</a>`)
	} else {
		c.WriteString(`<a`)
		c.WriteString(" class=\"btn btn-primary btn-lg\"")
		c.WriteString(" href=\"/login\"")
		c.WriteString(">")
		c.WriteString(`Sign in`)
		c.WriteString(`</a>`)
	}
	c.WriteString(`</div>`)
	c.WriteString(`<p`)
	c.WriteString(" class=\"muted\"")
	c.WriteString(">")
	c.WriteString(html.EscapeString(fmt.Sprint(p.Home.UserCount)))
	c.WriteString(` users in libraVDB`)
	c.WriteString(`</p>`)
	c.WriteString(`</section>`)
	if err := RenderCounterWidget(c, map[string]any{"count": p.Home.Counter, "feature": p.Home.Feature}, nil); err != nil { return err }
	c.WriteString(`<section`)
	c.WriteString(" class=\"card\"")
	c.WriteString(">")
	c.WriteString(`<h2>`)
	c.WriteString(`Leaderboard — a graph query`)
	c.WriteString(`</h2>`)
	c.WriteString(`<p`)
	c.WriteString(" class=\"muted\"")
	c.WriteString(">")
	c.WriteString(`Top users by follower count, computed with libraVDB
            `)
	c.WriteString(`<code>`)
	c.WriteString(`JOIN MATCH`)
	c.WriteString(`</code>`)
	c.WriteString(` over the FOLLOWS graph.
        `)
	c.WriteString(`</p>`)
	c.WriteString(`<ol`)
	c.WriteString(" class=\"leaderboard\"")
	c.WriteString(">")
	for _, f := range p.Home.FollowerTop {
		c.WriteString(`<li>`)
		c.WriteString(`<strong>`)
		c.WriteString(html.EscapeString(fmt.Sprint(f.Name)))
		c.WriteString(`</strong>`)
		c.WriteString(`<span`)
		c.WriteString(" class=\"muted\"")
		c.WriteString(">")
		c.WriteString(`@`)
		c.WriteString(html.EscapeString(fmt.Sprint(f.ID)))
		c.WriteString(` · `)
		c.WriteString(html.EscapeString(fmt.Sprint(f.Followers)))
		c.WriteString(` followers`)
		c.WriteString(`</span>`)
		c.WriteString(`</li>`)
	}
	c.WriteString(`</ol>`)
	c.WriteString(`</section>`)
return nil
}

func RegisterHome(e *gsx.Engine) {
	e.Register("Home", func(c *render.ComponentContext, data any) error {
	return RenderHome(c, data.(models.Page), nil)
	})
}

