// Code generated by nanite-gsx. DO NOT EDIT.

package views

import (
"fmt"
"html"
"github.com/xDarkicex/gsx-demo/models"

"github.com/xDarkicex/nanite-gsx"
"github.com/xDarkicex/nanite-render"
)

type AppLayout struct{}


func RenderAppLayout(c *render.ComponentContext, p models.Page, children func(c *render.ComponentContext) error) error {
	c.WriteString(`<html`)
	c.WriteString(" lang=\"en\"")
	c.WriteString(">")
	c.WriteString(`<head>`)
	c.WriteString(`<meta`)
	c.WriteString(" charset=\"utf-8\"")
	c.WriteString(">")
	c.WriteString(`</meta>`)
	c.WriteString(`<meta`)
	c.WriteString(" name=\"viewport\"")
	c.WriteString(" content=\"width=device-width, initial-scale=1\"")
	c.WriteString(">")
	c.WriteString(`</meta>`)
	c.WriteString(`<title>`)
	c.WriteString(`gsx-demo — nanite · nanite-render · nanite-gsx · libraVDB`)
	c.WriteString(`</title>`)
	c.WriteString(`<link`)
	c.WriteString(" rel=\"stylesheet\"")
	c.WriteString(" href=\"/static/app.css\"")
	c.WriteString(">")
	c.WriteString(`</link>`)
	c.WriteString(`<script`)
	c.WriteString(" defer=\"\"")
	c.WriteString(" src=\"https://cdn.jsdelivr.net/npm/alpinejs@3.14.1/dist/cdn.min.js\"")
	c.WriteString(">")
	c.WriteString(`</script>`)
	c.WriteString(`<script`)
	c.WriteString(" defer=\"\"")
	c.WriteString(" src=\"https://cdn.jsdelivr.net/npm/htmx.org@2.0.4/dist/htmx.min.js\"")
	c.WriteString(">")
	c.WriteString(`</script>`)
	c.WriteString(`</head>`)
	c.WriteString(`<body>`)
	if err := RenderNavbar(c, p, nil); err != nil { return err }
	c.WriteString(`<main`)
	c.WriteString(" class=\"container\"")
	c.WriteString(">")
	if err := c.Yield(); err != nil { return err }
	c.WriteString(`</main>`)
	c.WriteString(`<footer`)
	c.WriteString(" class=\"footer\"")
	c.WriteString(">")
	c.WriteString(`<p`)
	c.WriteString(" class=\"muted\"")
	c.WriteString(">")
	c.WriteString(`gsx-demo · compiled to Go, rendered by nanite-render, stored in libraVDB`)
	c.WriteString(`</p>`)
	c.WriteString(`</footer>`)
	c.WriteString(`</body>`)
	c.WriteString(`</html>`)
return nil
}

func RegisterAppLayout(e *gsx.Engine) {
	e.Register("AppLayout", func(c *render.ComponentContext, data any) error {
	return RenderAppLayout(c, data.(models.Page), nil)
	})
}



type Navbar struct{}

func RenderNavbar(c *render.ComponentContext, page models.Page, children func(c *render.ComponentContext) error) error {
	c.WriteString(`<nav`)
	c.WriteString(" class=\"navbar\"")
	c.WriteHydrateProps("x-data", map[string]any{"open": false})
	c.WriteString(">")
	c.WriteString(`<a`)
	c.WriteString(" href=\"/\"")
	c.WriteString(" class=\"brand\"")
	c.WriteString(">")
	c.WriteString(`&lt;/&gt;&nbsp;gsx-demo`)
	c.WriteString(`</a>`)
	c.WriteString(`<div`)
	c.WriteString(" class=\"nav-right\"")
	c.WriteString(">")
	if page.User != nil {
		c.WriteString(`<span`)
		c.WriteString(" class=\"nav-link muted\"")
		c.WriteString(">")
		c.WriteString(`Signed in as `)
		c.WriteString(html.EscapeString(fmt.Sprint(page.User.Name)))
		c.WriteString(`</span>`)
		c.WriteString(`<a`)
		c.WriteString(" class=\"nav-link\"")
		c.WriteString(" href=\"/dashboard\"")
		c.WriteString(">")
		c.WriteString(`Dashboard`)
		c.WriteString(`</a>`)
		c.WriteString(`<button`)
		c.WriteString(" class=\"btn btn-sm\"")
		c.WriteString(" @click=\"open = !open\"")
		c.WriteString(">")
		c.WriteString(`Menu ▾
                `)
		c.WriteString(`</button>`)
		c.WriteString(`<div`)
		c.WriteString(" class=\"nav-menu\"")
		c.WriteString(" x-show=\"open\"")
		c.WriteString(" x-cloak=\"\"")
		c.WriteString(" @click.away=\"open = false\"")
		c.WriteString(">")
		c.WriteString(`<form`)
		c.WriteString(" method=\"post\"")
		c.WriteString(" action=\"/logout\"")
		c.WriteString(">")
		c.WriteString(`<button`)
		c.WriteString(" type=\"submit\"")
		c.WriteString(" class=\"btn btn-sm btn-block\"")
		c.WriteString(">")
		c.WriteString(`Log out`)
		c.WriteString(`</button>`)
		c.WriteString(`</form>`)
		c.WriteString(`</div>`)
	} else {
		c.WriteString(`<a`)
		c.WriteString(" class=\"nav-link\"")
		c.WriteString(" href=\"/login\"")
		c.WriteString(">")
		c.WriteString(`Sign in`)
		c.WriteString(`</a>`)
	}
	c.WriteString(`</div>`)
	c.WriteString(`</nav>`)
return nil
}

func RegisterNavbar(e *gsx.Engine) {
	e.Register("Navbar", func(c *render.ComponentContext, data any) error {
	return RenderNavbar(c, data.(models.Page), nil)
	})
}

