// Code generated by nanite-gsx. DO NOT EDIT.

package views

import (
"fmt"
"html"
"github.com/xDarkicex/gsx-demo/models"

"github.com/xDarkicex/nanite-gsx"
"github.com/xDarkicex/nanite-render"
)

type Login struct{}


func RenderLogin(c *render.ComponentContext, p models.Page, children func(c *render.ComponentContext) error) error {
	c.WriteString(`<div`)
	c.WriteString(" class=\"auth-shell\"")
	c.WriteString(">")
	c.WriteString(`<div`)
	c.WriteString(" class=\"auth-card\"")
	c.WriteString(">")
	c.WriteString(`<div`)
	c.WriteString(" class=\"card-heading\"")
	c.WriteString(">")
	c.WriteString(`<div>`)
	c.WriteString(`<div`)
	c.WriteString(" class=\"card-kicker\"")
	c.WriteString(">")
	c.WriteString(`Welcome back`)
	c.WriteString(`</div>`)
	c.WriteString(`<h2>`)
	c.WriteString(`Sign in to gsx-studio`)
	c.WriteString(`</h2>`)
	c.WriteString(`</div>`)
	c.WriteString(`</div>`)
	c.WriteString(`<p`)
	c.WriteString(" class=\"page-subtitle\"")
	c.WriteString(">")
	c.WriteString(`Demo account: `)
	c.WriteString(`<code>`)
	c.WriteString(`alice&#64;demo.dev`)
	c.WriteString(`</code>`)
	c.WriteString(` / `)
	c.WriteString(`<code>`)
	c.WriteString(`demo123`)
	c.WriteString(`</code>`)
	c.WriteString(`</p>`)
	if p.Login.Error != "" {
		c.WriteString(`<div`)
		c.WriteString(" class=\"notice notice-error\"")
		c.WriteString(">")
		c.WriteString(`<span`)
		c.WriteString(" class=\"notice-icon\"")
		c.WriteString(">")
		c.WriteString(`✕`)
		c.WriteString(`</span>`)
		c.WriteString(html.EscapeString(fmt.Sprint(p.Login.Error)))
		c.WriteString(`</div>`)
	}
	c.WriteString(`<form`)
	c.WriteString(" method=\"post\"")
	c.WriteString(" action=\"/login\"")
	c.WriteString(">")
	c.WriteString(`<div`)
	c.WriteString(" class=\"field\"")
	c.WriteString(">")
	c.WriteString(`<label`)
	c.WriteString(" class=\"uk-form-label\"")
	c.WriteString(" for=\"login-email\"")
	c.WriteString(">")
	c.WriteString(`Email`)
	c.WriteString(`</label>`)
	c.WriteString(`<input`)
	c.WriteString(" id=\"login-email\"")
	c.WriteString(" class=\"uk-input\"")
	c.WriteString(" type=\"email\"")
	c.WriteString(" name=\"email\"")
	c.WriteString(" placeholder=\"you@example.com\"")
	c.WriteString(" value=\"")
	c.WriteString(html.EscapeString(fmt.Sprint(p.Login.Email)))
	c.WriteString("\"")
	c.WriteString(" autofocus=\"\"")
	c.WriteString(">")
	c.WriteString(`</input>`)
	c.WriteString(`</div>`)
	c.WriteString(`<div`)
	c.WriteString(" class=\"field\"")
	c.WriteString(">")
	c.WriteString(`<label`)
	c.WriteString(" class=\"uk-form-label\"")
	c.WriteString(" for=\"login-password\"")
	c.WriteString(">")
	c.WriteString(`Password`)
	c.WriteString(`</label>`)
	c.WriteString(`<input`)
	c.WriteString(" id=\"login-password\"")
	c.WriteString(" class=\"uk-input\"")
	c.WriteString(" type=\"password\"")
	c.WriteString(" name=\"password\"")
	c.WriteString(" placeholder=\"••••••••\"")
	c.WriteString(">")
	c.WriteString(`</input>`)
	c.WriteString(`</div>`)
	c.WriteString(`<div`)
	c.WriteString(" class=\"form-actions\"")
	c.WriteString(">")
	c.WriteString(`<button`)
	c.WriteString(" type=\"submit\"")
	c.WriteString(" class=\"uk-button uk-button-primary\"")
	c.WriteString(">")
	c.WriteString(`Sign in`)
	c.WriteString(`</button>`)
	c.WriteString(`</div>`)
	c.WriteString(`</form>`)
	c.WriteString(`<p`)
	c.WriteString(" class=\"muted small\"")
	c.WriteString(">")
	c.WriteString(`bcrypt against libraVDB · signed session cookie ·
                nanite middleware guards /dashboard
            `)
	c.WriteString(`</p>`)
	c.WriteString(`</div>`)
	c.WriteString(`</div>`)
return nil
}

func RegisterLogin(e *gsx.Engine) {
	e.Register("Login", func(c *render.ComponentContext, data any) error {
	return RenderLogin(c, data.(models.Page), nil)
	})
}

