// Code generated by nanite-gsx. DO NOT EDIT.

package views

import (
"fmt"
"html"
"github.com/xDarkicex/gsx-demo/models"

"github.com/xDarkicex/nanite-gsx"
"github.com/xDarkicex/nanite-render"
)

type Login struct{}


func RenderLogin(c *render.ComponentContext, p models.Page, children func(c *render.ComponentContext) error) error {
	c.WriteString(`<section`)
	c.WriteString(" class=\"card login-card\"")
	c.WriteString(">")
	c.WriteString(`<h1>`)
	c.WriteString(`Sign in`)
	c.WriteString(`</h1>`)
	c.WriteString(`<p`)
	c.WriteString(" class=\"muted\"")
	c.WriteString(">")
	c.WriteString(`Demo account: `)
	c.WriteString(`<code>`)
	c.WriteString(`alice`)
	c.WriteString(`@`)
	c.WriteString(`demo.dev`)
	c.WriteString(`</code>`)
	c.WriteString(` / `)
	c.WriteString(`<code>`)
	c.WriteString(`demo123`)
	c.WriteString(`</code>`)
	c.WriteString(`</p>`)
	if p.Login.Error != "" {
		c.WriteString(`<p`)
		c.WriteString(" class=\"flash-error\"")
		c.WriteString(">")
		c.WriteString(html.EscapeString(fmt.Sprint(p.Login.Error)))
		c.WriteString(`</p>`)
	}
	c.WriteString(`<form`)
	c.WriteString(" method=\"post\"")
	c.WriteString(" action=\"/login\"")
	c.WriteString(" class=\"form\"")
	c.WriteString(">")
	c.WriteString(`<label>`)
	c.WriteString(`Email
                `)
	c.WriteString(`<input`)
	c.WriteString(" type=\"email\"")
	c.WriteString(" name=\"email\"")
	c.WriteString(" placeholder=\"you@example.com\"")
	c.WriteString(" value=\"")
	c.WriteString(html.EscapeString(fmt.Sprint(p.Login.Email)))
	c.WriteString("\"")
	c.WriteString(" autofocus=\"\"")
	c.WriteString(">")
	c.WriteString(`</input>`)
	c.WriteString(`</label>`)
	c.WriteString(`<label>`)
	c.WriteString(`Password
                `)
	c.WriteString(`<input`)
	c.WriteString(" type=\"password\"")
	c.WriteString(" name=\"password\"")
	c.WriteString(" placeholder=\"••••••••\"")
	c.WriteString(">")
	c.WriteString(`</input>`)
	c.WriteString(`</label>`)
	c.WriteString(`<button`)
	c.WriteString(" type=\"submit\"")
	c.WriteString(" class=\"btn btn-primary btn-block\"")
	c.WriteString(">")
	c.WriteString(`Sign in`)
	c.WriteString(`</button>`)
	c.WriteString(`</form>`)
	c.WriteString(`<p`)
	c.WriteString(" class=\"muted small\"")
	c.WriteString(">")
	c.WriteString(`Auth flow: bcrypt check against libraVDB, signed session
            cookie, nanite middleware guarding /dashboard.
        `)
	c.WriteString(`</p>`)
	c.WriteString(`</section>`)
return nil
}

func RegisterLogin(e *gsx.Engine) {
	e.Register("Login", func(c *render.ComponentContext, data any) error {
	return RenderLogin(c, data.(models.Page), nil)
	})
}

