// Code generated by nanite-gsx. DO NOT EDIT.

package views

import (
"fmt"
"html"
"github.com/xDarkicex/gsx-demo/models"

"github.com/xDarkicex/nanite-gsx"
"github.com/xDarkicex/nanite-render"
)

type Overview struct{}


func RenderOverview(c *render.ComponentContext, p models.Page, children func(c *render.ComponentContext) error) error {
	c.WriteString(`<h1`)
	c.WriteString(" class=\"uk-h2\"")
	c.WriteString(">")
	c.WriteString(`Overview`)
	c.WriteString(`</h1>`)
	c.WriteString(`<p`)
	c.WriteString(" class=\"muted\"")
	c.WriteString(">")
	c.WriteString(`project demo · nanite stack`)
	c.WriteString(`</p>`)
	c.WriteString(`<div`)
	c.WriteString(" class=\"uk-grid uk-child-width-1-4@m uk-grid-small\"")
	c.WriteString(">")
	if err := RenderStatCard(c, "Users", p.Dash.Stats.Users, "👥", nil); err != nil { return err }
	if err := RenderStatCard(c, "Follow edges", p.Dash.Stats.Following, "→", nil); err != nil { return err }
	if err := RenderStatCard(c, "Todos", p.Dash.Stats.Todos, "✅", nil); err != nil { return err }
	if err := RenderStatCard(c, "Clicks", p.Dash.Stats.Clicks, "🖱️", nil); err != nil { return err }
	c.WriteString(`</div>`)
	c.WriteString(`<div`)
	c.WriteString(" class=\"uk-grid uk-child-width-1-2@m uk-grid-medium uk-margin-top\"")
	c.WriteString(">")
	c.WriteString(`<div`)
	c.WriteString(" class=\"uk-card uk-card-default uk-card-body\"")
	c.WriteString(">")
	c.WriteString(`<h3`)
	c.WriteString(" class=\"uk-h4\"")
	c.WriteString(">")
	c.WriteString(`Todo priority distribution`)
	c.WriteString(`</h3>`)
	c.WriteString(`<p`)
	c.WriteString(" class=\"muted small\"")
	c.WriteString(">")
	c.WriteString(`GROUP BY priority — libraVDB aggregate`)
	c.WriteString(`</p>`)
	c.WriteString(`<div`)
	c.WriteString(" class=\"bars\"")
	c.WriteString(">")
	for _, b := range p.Dash.Bars {
		c.WriteString(`<div`)
		c.WriteString(" class=\"bar-row\"")
		c.WriteString(">")
		c.WriteString(`<span`)
		c.WriteString(" class=\"bar-label muted\"")
		c.WriteString(">")
		c.WriteString(html.EscapeString(fmt.Sprint(b.Label)))
		c.WriteString(`</span>`)
		c.WriteString(`<div`)
		c.WriteString(" class=\"bar-track\"")
		c.WriteString(">")
		c.WriteString(`<div`)
		c.WriteString(" class=\"bar-fill\"")
		c.WriteString(" style=\"")
		c.WriteString(html.EscapeString(fmt.Sprint(barWidth(b.Count, p.Dash.MaxBar))))
		c.WriteString("\"")
		c.WriteString(">")
		c.WriteString(`</div>`)
		c.WriteString(`</div>`)
		c.WriteString(`<span`)
		c.WriteString(" class=\"bar-count\"")
		c.WriteString(">")
		c.WriteString(html.EscapeString(fmt.Sprint(b.Count)))
		c.WriteString(`</span>`)
		c.WriteString(`</div>`)
	}
	if len(p.Dash.Bars) == 0 {
		c.WriteString(`<p`)
		c.WriteString(" class=\"muted\"")
		c.WriteString(">")
		c.WriteString(`No todos yet.`)
		c.WriteString(`</p>`)
	}
	c.WriteString(`</div>`)
	c.WriteString(`</div>`)
	c.WriteString(`<div>`)
	c.WriteString(`<div`)
	c.WriteString(" id=\"liveclock\"")
	c.WriteString(" hx-get=\"/widgets/clock\"")
	c.WriteString(" hx-trigger=\"load\"")
	c.WriteString(" hx-swap=\"innerHTML\"")
	c.WriteString(">")
	c.WriteString(`</div>`)
	c.WriteString(`<div`)
	c.WriteString(" class=\"uk-card uk-card-default uk-card-body uk-margin-top\"")
	c.WriteString(">")
	c.WriteString(`<h3`)
	c.WriteString(" class=\"uk-h4\"")
	c.WriteString(">")
	c.WriteString(`Recently followed`)
	c.WriteString(`</h3>`)
	c.WriteString(`<ul`)
	c.WriteString(" class=\"uk-list uk-list-divider\"")
	c.WriteString(">")
	for _, f := range p.Dash.Following {
		c.WriteString(`<li>`)
		c.WriteString(html.EscapeString(fmt.Sprint(f.Name)))
		c.WriteString(`<span`)
		c.WriteString(" class=\"muted\"")
		c.WriteString(">")
		c.WriteString(`&#64;`)
		c.WriteString(html.EscapeString(fmt.Sprint(f.ID)))
		c.WriteString(`</span>`)
		c.WriteString(`</li>`)
	}
	if len(p.Dash.Following) == 0 {
		c.WriteString(`<li`)
		c.WriteString(" class=\"muted\"")
		c.WriteString(">")
		c.WriteString(`Nobody yet.`)
		c.WriteString(`</li>`)
	}
	c.WriteString(`</ul>`)
	c.WriteString(`</div>`)
	c.WriteString(`</div>`)
	c.WriteString(`</div>`)
return nil
}

func RegisterOverview(e *gsx.Engine) {
	e.Register("Overview", func(c *render.ComponentContext, data any) error {
	return RenderOverview(c, data.(models.Page), nil)
	})
}

