// Code generated by nanite-gsx. DO NOT EDIT.

package views

import (
"fmt"
"html"
"github.com/xDarkicex/gsx-demo/models"

"github.com/xDarkicex/nanite-gsx"
"github.com/xDarkicex/nanite-render"
)

type ProfilePage struct{}


func RenderProfilePage(c *render.ComponentContext, p models.Page, children func(c *render.ComponentContext) error) error {
	c.WriteString(`<div`)
	c.WriteString(" class=\"profile-head\"")
	c.WriteString(">")
	c.WriteString(`<span`)
	c.WriteString(" class=\"list-avatar profile-avatar\"")
	c.WriteString(">")
	c.WriteString(html.EscapeString(fmt.Sprint(userInitial(p.Profile.User.Name))))
	c.WriteString(`</span>`)
	c.WriteString(`<div`)
	c.WriteString(" class=\"profile-meta\"")
	c.WriteString(">")
	c.WriteString(`<h1>`)
	c.WriteString(html.EscapeString(fmt.Sprint(p.Profile.User.Name)))
	c.WriteString(`</h1>`)
	c.WriteString(`<p`)
	c.WriteString(" class=\"muted\"")
	c.WriteString(">")
	c.WriteString(`&#64;`)
	c.WriteString(html.EscapeString(fmt.Sprint(p.Profile.User.ID)))
	c.WriteString(` · `)
	c.WriteString(html.EscapeString(fmt.Sprint(p.Profile.User.Email)))
	c.WriteString(`</p>`)
	c.WriteString(`<p`)
	c.WriteString(" class=\"muted small\"")
	c.WriteString(">")
	c.WriteString(`member since `)
	c.WriteString(html.EscapeString(fmt.Sprint(p.Profile.User.CreatedAt)))
	c.WriteString(`</p>`)
	c.WriteString(`</div>`)
	if !p.Profile.IsSelf {
		c.WriteString(`<li`)
		c.WriteString(" class=\"profile-follow\"")
		c.WriteString(">")
		if err := RenderFollowButton(c, map[string]any{
                    "target_id": p.Profile.User.ID, "followed": p.Profile.Followed,
                }, nil); err != nil { return err }
		c.WriteString(`</li>`)
	}
	c.WriteString(`</div>`)
	c.WriteString(`<div`)
	c.WriteString(" class=\"stat-grid\"")
	c.WriteString(">")
	if err := RenderStatCard(c, "Following", p.Profile.FollowingCount, "→", nil); err != nil { return err }
	if err := RenderStatCard(c, "Followers", p.Profile.FollowerCount, "←", nil); err != nil { return err }
	c.WriteString(`</div>`)
	c.WriteString(`<section`)
	c.WriteString(" class=\"dashboard-card\"")
	c.WriteString(">")
	c.WriteString(`<div`)
	c.WriteString(" class=\"card-heading\"")
	c.WriteString(">")
	c.WriteString(`<div>`)
	c.WriteString(`<div`)
	c.WriteString(" class=\"card-kicker\"")
	c.WriteString(">")
	c.WriteString(`FOLLOWS graph`)
	c.WriteString(`</div>`)
	c.WriteString(`<h2>`)
	c.WriteString(`Following`)
	c.WriteString(`</h2>`)
	c.WriteString(`</div>`)
	c.WriteString(`<span`)
	c.WriteString(" class=\"record-count\"")
	c.WriteString(">")
	c.WriteString(html.EscapeString(fmt.Sprint(p.Profile.FollowingCount)))
	c.WriteString(`</span>`)
	c.WriteString(`</div>`)
	c.WriteString(`<ul`)
	c.WriteString(" class=\"clean-list\"")
	c.WriteString(">")
	for _, f := range p.Profile.Following {
		c.WriteString(`<li>`)
		c.WriteString(`<span`)
		c.WriteString(" class=\"list-avatar\"")
		c.WriteString(">")
		c.WriteString(html.EscapeString(fmt.Sprint(userInitial(f.Name))))
		c.WriteString(`</span>`)
		c.WriteString(`<span`)
		c.WriteString(" class=\"list-copy\"")
		c.WriteString(">")
		c.WriteString(`<strong>`)
		c.WriteString(html.EscapeString(fmt.Sprint(f.Name)))
		c.WriteString(`</strong>`)
		c.WriteString(`<span>`)
		c.WriteString(`<a`)
		c.WriteString(" href=\"")
		c.WriteString(html.EscapeString(fmt.Sprint("/profile/" + f.ID)))
		c.WriteString("\"")
		c.WriteString(">")
		c.WriteString(`&#64;`)
		c.WriteString(html.EscapeString(fmt.Sprint(f.ID)))
		c.WriteString(`</a>`)
		c.WriteString(`</span>`)
		c.WriteString(`</span>`)
		c.WriteString(`<a`)
		c.WriteString(" class=\"uk-button uk-button-small uk-button-ghost action-button\"")
		c.WriteString(" href=\"")
		c.WriteString(html.EscapeString(fmt.Sprint("/profile/" + f.ID)))
		c.WriteString("\"")
		c.WriteString(">")
		c.WriteString(`View profile`)
		c.WriteString(`</a>`)
		c.WriteString(`</li>`)
	}
	if len(p.Profile.Following) == 0 {
		c.WriteString(`<li`)
		c.WriteString(" class=\"empty-state\"")
		c.WriteString(">")
		c.WriteString(`Nobody yet.`)
		c.WriteString(`</li>`)
	}
	c.WriteString(`</ul>`)
	c.WriteString(`</section>`)
return nil
}

func RegisterProfilePage(e *gsx.Engine) {
	e.Register("ProfilePage", func(c *render.ComponentContext, data any) error {
	return RenderProfilePage(c, data.(models.Page), nil)
	})
}

