// Code generated by nanite-gsx. DO NOT EDIT.

package views

import (
"fmt"
"html"
"github.com/xDarkicex/gsx-demo/models"

"github.com/xDarkicex/nanite-gsx"
"github.com/xDarkicex/nanite-render"
)

type SettingsPage struct{}


func RenderSettingsPage(c *render.ComponentContext, p models.Page, children func(c *render.ComponentContext) error) error {
	c.WriteString(`<h1`)
	c.WriteString(" class=\"uk-h2\"")
	c.WriteString(">")
	c.WriteString(`Settings`)
	c.WriteString(`</h1>`)
	c.WriteString(`<p`)
	c.WriteString(" class=\"muted\"")
	c.WriteString(">")
	c.WriteString(`project demo`)
	c.WriteString(`</p>`)
	c.WriteString(`<div`)
	c.WriteString(" class=\"uk-card uk-card-default uk-card-body uk-width-1-2@m\"")
	c.WriteString(">")
	c.WriteString(`<dl`)
	c.WriteString(" class=\"uk-description-list\"")
	c.WriteString(">")
	c.WriteString(`<dt>`)
	c.WriteString(`Project`)
	c.WriteString(`</dt>`)
	c.WriteString(`<dd>`)
	c.WriteString(`demo`)
	c.WriteString(`</dd>`)
	c.WriteString(`<dt>`)
	c.WriteString(`Signed in as`)
	c.WriteString(`</dt>`)
	c.WriteString(`<dd>`)
	c.WriteString(html.EscapeString(fmt.Sprint(p.User.Name)))
	c.WriteString(` &#64;`)
	c.WriteString(html.EscapeString(fmt.Sprint(p.User.Email)))
	c.WriteString(`</dd>`)
	c.WriteString(`<dt>`)
	c.WriteString(`Stack`)
	c.WriteString(`</dt>`)
	c.WriteString(`<dd>`)
	c.WriteString(`nanite · nanite-render · nanite-gsx · libraVDB`)
	c.WriteString(`</dd>`)
	c.WriteString(`<dt>`)
	c.WriteString(`Session cookie`)
	c.WriteString(`</dt>`)
	c.WriteString(`<dd>`)
	c.WriteString(`<code>`)
	c.WriteString(`gsx_session`)
	c.WriteString(`</code>`)
	c.WriteString(` (HttpOnly, 7 days)`)
	c.WriteString(`</dd>`)
	c.WriteString(`</dl>`)
	c.WriteString(`<form`)
	c.WriteString(" method=\"post\"")
	c.WriteString(" action=\"/logout\"")
	c.WriteString(">")
	c.WriteString(`<button`)
	c.WriteString(" class=\"uk-button uk-button-danger\"")
	c.WriteString(">")
	c.WriteString(`Log out`)
	c.WriteString(`</button>`)
	c.WriteString(`</form>`)
	c.WriteString(`</div>`)
return nil
}

func RegisterSettingsPage(e *gsx.Engine) {
	e.Register("SettingsPage", func(c *render.ComponentContext, data any) error {
	return RenderSettingsPage(c, data.(models.Page), nil)
	})
}

