// Code generated by nanite-gsx. DO NOT EDIT.

package views

import (
"fmt"
"html"
"github.com/xDarkicex/gsx-demo/models"

"github.com/xDarkicex/nanite-gsx"
"github.com/xDarkicex/nanite-render"
)

type SQLPage struct{}


func RenderSQLPage(c *render.ComponentContext, p models.Page, children func(c *render.ComponentContext) error) error {
	c.WriteString(`<h1`)
	c.WriteString(" class=\"uk-h2\"")
	c.WriteString(">")
	c.WriteString(`SQL Editor`)
	c.WriteString(`</h1>`)
	c.WriteString(`<p`)
	c.WriteString(" class=\"muted\"")
	c.WriteString(">")
	c.WriteString(`run anything — `)
	c.WriteString(`<code>`)
	c.WriteString(`SELECT`)
	c.WriteString(`</code>`)
	c.WriteString(`,`)
	c.WriteString(`<code>`)
	c.WriteString(`INSERT`)
	c.WriteString(`</code>`)
	c.WriteString(`,`)
	c.WriteString(`<code>`)
	c.WriteString(`UPDATE`)
	c.WriteString(`</code>`)
	c.WriteString(`,`)
	c.WriteString(`<code>`)
	c.WriteString(`VERSIONS OF`)
	c.WriteString(`</code>`)
	c.WriteString(`…`)
	c.WriteString(`</p>`)
	c.WriteString(`<form`)
	c.WriteString(" hx-post=\"/dashboard/sql/run\"")
	c.WriteString(" hx-target=\"#sql-results\"")
	c.WriteString(" hx-swap=\"outerHTML\"")
	c.WriteString(" class=\"uk-margin-bottom\"")
	c.WriteString(">")
	c.WriteString(`<textarea`)
	c.WriteString(" name=\"sql\"")
	c.WriteString(" rows=\"8\"")
	c.WriteString(" class=\"uk-textarea uk-font-mono\"")
	c.WriteString(" placeholder=\"SELECT id, title FROM todos\"")
	c.WriteString(">")
	c.WriteString(html.EscapeString(fmt.Sprint(p.Dash.SQLText)))
	c.WriteString(`</textarea>`)
	c.WriteString(`<div`)
	c.WriteString(" class=\"uk-margin-top\"")
	c.WriteString(">")
	c.WriteString(`<button`)
	c.WriteString(" class=\"uk-button uk-button-primary\"")
	c.WriteString(">")
	c.WriteString(`Run`)
	c.WriteString(`</button>`)
	c.WriteString(`</div>`)
	c.WriteString(`</form>`)
	c.WriteString(`<div`)
	c.WriteString(" id=\"sql-results\"")
	c.WriteString(">")
	if err := RenderSQLResults(c, map[string]any{
            "error": p.Dash.SQLError, "columns": p.Dash.SQLColumns,
            "rows": p.Dash.SQLRows, "text": p.Dash.SQLText,
        }, nil); err != nil { return err }
	c.WriteString(`</div>`)
return nil
}

func RegisterSQLPage(e *gsx.Engine) {
	e.Register("SQLPage", func(c *render.ComponentContext, data any) error {
	return RenderSQLPage(c, data.(models.Page), nil)
	})
}



type SQLResults struct{}

func RenderSQLResults(c *render.ComponentContext, props map[string]any, children func(c *render.ComponentContext) error) error {
	if props["error"].(string) != "" {
		c.WriteString(`<div`)
		c.WriteString(" class=\"uk-alert uk-alert-danger\"")
		c.WriteString(">")
		c.WriteString(`<pre`)
		c.WriteString(" class=\"uk-margin-remove\"")
		c.WriteString(">")
		c.WriteString(html.EscapeString(fmt.Sprint(props["error"].(string))))
		c.WriteString(`</pre>`)
		c.WriteString(`</div>`)
	}
	if props["columns"] != nil {
		c.WriteString(`<div`)
		c.WriteString(" class=\"uk-card uk-card-default\"")
		c.WriteString(">")
		c.WriteString(`<div`)
		c.WriteString(" class=\"uk-card-header\"")
		c.WriteString(">")
		c.WriteString(`<div`)
		c.WriteString(" class=\"muted small\"")
		c.WriteString(">")
		c.WriteString(html.EscapeString(fmt.Sprint(len(props["rows"].([][]string)))))
		c.WriteString(` rows`)
		c.WriteString(`</div>`)
		c.WriteString(`</div>`)
		c.WriteString(`<div`)
		c.WriteString(" class=\"uk-overflow-auto\"")
		c.WriteString(">")
		c.WriteString(`<table`)
		c.WriteString(" class=\"uk-table uk-table-hover uk-table-divider uk-table-small\"")
		c.WriteString(">")
		c.WriteString(`<thead>`)
		c.WriteString(`<tr>`)
		for _, __c := range props["columns"].([]string) {
			c.WriteString(`<th>`)
			c.WriteString(html.EscapeString(fmt.Sprint(__c)))
			c.WriteString(`</th>`)
		}
		c.WriteString(`</tr>`)
		c.WriteString(`</thead>`)
		c.WriteString(`<tbody>`)
		for _, row := range props["rows"].([][]string) {
			c.WriteString(`<tr>`)
			for _, cell := range row {
				c.WriteString(`<td`)
				c.WriteString(" class=\"small\"")
				c.WriteString(">")
				c.WriteString(html.EscapeString(fmt.Sprint(cell)))
				c.WriteString(`</td>`)
			}
			c.WriteString(`</tr>`)
		}
		if len(props["rows"].([][]string)) == 0 {
			c.WriteString(`<tr>`)
			c.WriteString(`<td`)
			c.WriteString(" colspan=\"")
			c.WriteString(html.EscapeString(fmt.Sprint(len(props["columns"].([]string)))))
			c.WriteString("\"")
			c.WriteString(" class=\"muted\"")
			c.WriteString(">")
			c.WriteString(`Success. No rows returned.`)
			c.WriteString(`</td>`)
			c.WriteString(`</tr>`)
		}
		c.WriteString(`</tbody>`)
		c.WriteString(`</table>`)
		c.WriteString(`</div>`)
		c.WriteString(`</div>`)
	}
return nil
}

func RegisterSQLResults(e *gsx.Engine) {
	e.Register("SQLResults", func(c *render.ComponentContext, data any) error {
	return RenderSQLResults(c, data.(map[string]any), nil)
	})
}

